In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def prepend_ones(X):
    # adds a column of ones before the first column of a matrix
    return np.insert(X, 0, 1, axis=1)

def sigmoid(z):
    # computes the logistic function for a number or each element of an array
    return 1 / (1 + np.exp(-z))


In [3]:
# network layout: number of examples, features, hidden layers and classes

# data
num_examples = 1 # number of examples in the training data set
num_features = 3 # number of features (e.g. number of pixels in a picture)
num_classes  = 2 # number of different labels (e.g. 10 for digits from 0 to 9)

# hidden layer
num_hidden = 3 # number of nodes in the hidden layer

In [77]:
# Check if your code executes without any errors. 
# For this, use matrices with random numbers

# data, size=(num_examples,num_features)
X = np.random.uniform(0, 10, size=(num_examples,num_features))
Xp1 = # ... prepend ones

# random arrays of weights
W1 = np.random.uniform(0, 1, size=(num_features + 1, num_hidden)) # weights for X -> hidden layer
W2 = np.random.uniform(0, 1, size=(num_hidden + 1, num_classes)) # weights for hidden -> Y_hat

# propagate the input X through your network
# 1) input -> hidden variables
H = np.matmul(...) # ... multiply matrices
Hp1 =  # ... prepend ones
# 2) hidden variables -> output 
y_hat = # ... multipy matrices

print('y_hat = ', y_hat)

y_hat =  [[9.29133515 8.63806753]]


In [83]:
# Now use custom matrices

# ====================================
# input data X
X = np.zeros((num_examples,num_features))
# custom modify your matrix:
X[0,0] = 1
X[0,1] = 1
X[0,2] = 2

Xp1 = prepend_ones(X)


# ====================================
# weights W1, W2
W1 = np.zeros((num_features + 1, num_hidden)) # input -> hidden layer
# custom modify your matrix:
W1[1:,:] = 1

W2 = np.zeros((num_hidden + 1, num_classes)) # hidden -> output
# custom modify your matrix:
W2[1,:] = 1


# ====================================
# propagate the input X through your network
# 1) input -> hidden variables
H = np.matmul(Xp1, W1)
Hp1 = prepend_ones(H)

# 2) hidden variables -> output
y_hat = np.matmul(Hp1, W2)


# ====================================
# print
print('Xp1 = \n', Xp1)
print('W1 = \n', W1)
print('Hp1 = \n', Hp1)
print('W2 = \n', W2)
print('y_hat = \n', y_hat)

Xp1 = 
 [[1. 1. 1. 2.]]
W1 = 
 [[0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Hp1 = 
 [[1. 4. 4. 4.]]
W2 = 
 [[0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
y_hat = 
 [[4. 4.]]
